### ISSUE TITLE
TestCases for ratelimiter, timelimiter, thread-pool-bulkhead and bulkhead

### ISSUE THREAD

**Issue by nagkumar** [resilience4j/resilience4j-spring-boot3-demo#7]
```
resilience4j.bulkhead:
    configs:
        default:
            maxConcurrentCalls: 100
    instances:
        backendA:
            maxConcurrentCalls: 10
        backendB:
            maxWaitDuration: 10ms
            maxConcurrentCalls: 20

resilience4j.thread-pool-bulkhead:
    configs:
        default:
            maxThreadPoolSize: 4
            coreThreadPoolSize: 2
            queueCapacity: 2
    instances:
        backendA:
            baseConfig: default
        backendB:
            maxThreadPoolSize: 1
            coreThreadPoolSize: 1
            queueCapacity: 1

resilience4j.ratelimiter:
    configs:
        default:
            registerHealthIndicator: false
            limitForPeriod: 10
            limitRefreshPeriod: 1s
            timeoutDuration: 0
            eventConsumerBufferSize: 100
    instances:
        backendA:
            baseConfig: default
        backendB:
            limitForPeriod: 6
            limitRefreshPeriod: 500ms
            timeoutDuration: 3s

resilience4j.timelimiter:
    configs:
        default:
            cancelRunningFuture: false
            timeoutDuration: 2s
    instances:
        backendA:
            baseConfig: default
        backendB:
            baseConfig: default

```

all these are configured in the application.yaml however

` private final RateLimiter rateLimiter;` variable declared in BackendBControl is unused.
    
    may be testcases are missing..???

<img width="653" alt="image" src="https://github.com/resilience4j/resilience4j-spring-boot3-demo/assets/332234/b6333d1c-5586-471b-8b93-e58b2885db01">
